apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  clusterIP: None  # Headless service
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432