version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

  springboot:
    image: sugesh23/springboot-postgres:latest
    depends_on:
      - postgres
    ports:
      - "8081:80"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
