apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-postgres
  template:
    metadata:
      labels:
        app: springboot-postgres
    spec:
      containers:
        - name: springboot-postgres
          image: sugesh23/springboot-postgres:latest  # override in overlays
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          env:
            - name: DB_HOST
              value: postgres-0.postgres.springboot-app.svc.cluster.local  # overridden by overlay
            - name: DB_PORT
              value: "5432"  # default, override if needed
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret  # override via overlay namePrefix
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 5