apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: bXlkYg==                   # base64 of "mydb"
  POSTGRES_USER: cG9zdGdyZXM=             # base64 of "postgres"
  POSTGRES_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==  # base64 of "mysecretpassword"