apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-postgres
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081  # Optional: fixed external port
  type: NodePort